### ISSUE TITLE
Master set

### ISSUE THREAD

**Issue by aaronbell** [Omnibus-Type/Faustina#6]
I note that there are 5 masters included in the font. Are all of these masters necessary? It appears that some, at least, are simply interpolated (for example, the positional error on ‰ in Medium looks like an interpolation error). If not all are necessary, we could cut the master set down to just 3 (or even just 2). This would help with saving file size and simplify the source file for easier updates. Thanks!

**Comment by aaronbell** [comment]
Following up on this. Would it be alright if I reduced the # of masters?

**Comment by Yorlmar** [comment]
No problem @aaronbell , in any case, once it is done we check if there are not very notable modifications. This to ensure that the user is not affected by visible changes. Many thanks in advance!

**Comment by aaronbell** [comment]
Great! I'll submit a PR for your review.
